Repository Arquisoft/wiq_es05b, pull requests merged in 2024-03, with the labels that each got.

#69 Develop timer
  webapp/src/App.jsx
  webapp/src/views/Game.jsx
Labels: front-end

#110 Account and history views
  .github/workflows/release.yml
  docker-compose.yml
  gatewayservice/GatewayAPI.yaml
  gatewayservice/gateway-service.js
  gatewayservice/middleware/AuthMiddleware.js
  gatewayservice/middleware/AuthTokenMiddleware.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  gatewayservice/routes/historyRoutes.js
  gatewayservice/routes/usersRoutes.js
  history/.dockerignore
  history/.env
  history/Dockerfile
  history/HistoryAPI.yaml
  history/history-model.js
  history/history-service.js
  history/package-lock.json
  history/package.json
  history/repositories/saveRepository.js
  history/routes/routes.js
  users/authservice/AuthAPI.yaml
  users/authservice/routes/routes.js
  users/userservice/UserAPI.yaml
  users/userservice/repositories/userRepository.js
  users/userservice/routes/routes.js
  webapp/src/scripts/textFormat.js
  webapp/src/views/Account.jsx
  webapp/src/views/Game.jsx
  webapp/src/views/Login.jsx
  webapp/src/views/components/MyAvatar.jsx
  webapp/src/views/components/Nav.jsx
  webapp/src/views/components/SaveDetails.jsx
  webapp/src/views/components/SaveList.jsx
Labels: front-end, back-end

#111 Add history service and views
  .github/workflows/deploy.yml
  docker-compose.yml
  gatewayservice/GatewayAPI.yaml
  gatewayservice/gateway-service.js
  gatewayservice/middleware/AuthMiddleware.js
  gatewayservice/middleware/AuthTokenMiddleware.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
  gatewayservice/routes/historyRoutes.js
  gatewayservice/routes/usersRoutes.js
  history/.dockerignore
  history/.env
  history/Dockerfile
  history/HistoryAPI.yaml
  history/history-model.js
  history/history-service.js
  history/package-lock.json
  history/package.json
  history/repositories/saveRepository.js
  history/routes/routes.js
  users/authservice/AuthAPI.yaml
  users/authservice/routes/routes.js
  users/userservice/UserAPI.yaml
  users/userservice/repositories/userRepository.js
  users/userservice/routes/routes.js
  webapp/src/scripts/textFormat.js
  webapp/src/views/Account.jsx
  webapp/src/views/Game.jsx
  webapp/src/views/Login.jsx
  webapp/src/views/components/MyAvatar.jsx
  webapp/src/views/components/Nav.jsx
  webapp/src/views/components/SaveDetails.jsx
  webapp/src/views/components/SaveList.jsx
Labels: deployment
